[package]
name = "napoleon_amp"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
rfd = "0.16.0"
napoleon_amp_core = { path = "napoleon_amp_core" }
egui_extras = "0.33.3"
open = "5.3.3"