[package]
name = "napoleon_amp_core"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs-next = "2.0.0"
sanitize-filename = "0.6.0"
symphonia = { version = "0.5.4", features = ["mp3", "symphonia-bundle-mp3"] }
#serbytes = { git = "https://github.com/ltsoveranakin/serbytes.git" }
serbytes = { path = "../../serdata" }
serde = { version = "1.0.228", features = ["derive"] }
rodio = "0.21.1"